name: Deploy Staging and Production
on:
  push:
    branches: [ dev ]
jobs:
  staging:
    name: Distribute Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Replace API Key
          env:
            PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          run: |
            sed -i "s/PEXELS_API_KEY=.*/PEXELS_API_KEY=\"${PEXELS_API_KEY}\"/" gradle.properties

      - name: Insert shopify base url gradle secret
        run: echo IMAGE_BASE_URL_SHOPIFY='${{ secrets.IMAGE_BASE_URL_SHOPIFY }}' '' > gradle.properties

      - name: Assemble Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.GIF_LIVE_WALLPAPER_KEY_STORE_CI_CD }}
          alias: ${{ secrets.GIF_LIVE_WALLPAPER_ALIAS_CI_CD }}
          keyStorePassword: ${{ secrets.GIF_LIVE_WALLPAPER_KEY_STORE_PASSWORD_CI_CD }}
          keyPassword: ${{ secrets.GIF_LIVE_WALLPAPER_ALLAS_PASSWORD_CI_CD }}

      - name: Setup Authorization With Google Play Store
        run: echo '${{ secrets.GOOGLE_SERVICE_API_FIRST_CI_CD }}' > service_account.json

      - name: Deploy to Internal Channel
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJson: service_account.json
          packageName: com.ameerhamza.animatedgiflivewallpapers
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: 'completed'
          whatsNewDirectory: whatsNewDirectory/
